//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prototipo_1._3.BD.RRHH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_RRHH2Entities1 : DbContext
    {
        public BD_RRHH2Entities1()
            : base("name=BD_RRHH2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_departamento> tbl_departamento { get; set; }
        public virtual DbSet<tbl_empleado> tbl_empleado { get; set; }
        public virtual DbSet<tbl_expediente> tbl_expediente { get; set; }
        public virtual DbSet<tbl_registroIncapacidad> tbl_registroIncapacidad { get; set; }
        public virtual DbSet<tbl_roles> tbl_roles { get; set; }
        public virtual DbSet<tbl_solicitudVacaciones> tbl_solicitudVacaciones { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
    }
}
