//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prototipo_1._3.BD.RRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_expediente()
        {
            this.tbl_solicitudVacaciones = new HashSet<tbl_solicitudVacaciones>();
            this.tbl_usuario = new HashSet<tbl_usuario>();
        }
    
        public int Id_expediente { get; set; }
        public Nullable<int> Id_incapacidad { get; set; }
        public int Id_empleado { get; set; }
        public System.DateTime Fecha_ingreso { get; set; }
        public string Nivel_academico { get; set; }
        public int Seguro_social { get; set; }
        public int Hora_llegada { get; set; }
        public int Hora_salida { get; set; }
        public string Estado { get; set; }
        public byte[] Imagen { get; set; }

        public virtual tbl_empleado tbl_empleado { get; set; }
        public virtual tbl_registroIncapacidad tbl_registroIncapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_solicitudVacaciones> tbl_solicitudVacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuario> tbl_usuario { get; set; }
    }
}
