//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prototipo_1._3.BD.RRHH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_registroIncapacidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_registroIncapacidad()
        {
            this.tbl_expediente = new HashSet<tbl_expediente>();
        }
    
        public int Id_incapacidad { get; set; }
        public int Id_empleado { get; set; }
        [Required (ErrorMessage ="Digitar cantidad de dias")]
        //[DataType(DataType.Custom.)]
        [Range(0, int.MaxValue, ErrorMessage = "Por favor introducir un numero valido")]
        public int Cantidad_dias { get; set; }
        [Required(ErrorMessage = "Digitar el tipo de incapacidad")]
        public string Tipo_incapacidad { get; set; }
        [Required(ErrorMessage = "Digitar una descripcion")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "Digitar una fecha")]
        [DataType(DataType.Date)]
        public System.DateTime Fecha_emision { get; set; }
        [Required(ErrorMessage = "Digitar el centro emisor")]
        public string Centro_emisor { get; set; }
        [Required(ErrorMessage = "Digitar el nombre del documento")]
        public string Nombre_doc { get; set; }
        
        public bool Estado { get; set; }
    
        public virtual tbl_empleado tbl_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_expediente> tbl_expediente { get; set; }
    }
}
