//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prototipo_1._3.BD.RRHH
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_usuario
    {
        public int Id_usuario { get; set; }
        [Required (ErrorMessage ="Favor digitar el nombre")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Favor digitar la contraseña")]
        [DataType (DataType.Password)]
        public string Password { get; set; }
        public bool Estado { get; set; }
        public int Id_rol { get; set; }
        public int Id_expediente { get; set; }
        public int Id_empleado { get; set; }
    
        public virtual tbl_empleado tbl_empleado { get; set; }
        public virtual tbl_expediente tbl_expediente { get; set; }
        public virtual tbl_roles tbl_roles { get; set; }
    }
}
