//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prototipo_1._3.BD.RRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_solicitudVacaciones
    {
        public int Id_solicitud { get; set; }
        public int Id_expediente { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public System.DateTime Fecha_final { get; set; }
        public string Condicion { get; set; }
        public int Total_dias { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual tbl_expediente tbl_expediente { get; set; }
    }
}
